[GOOGLE]
GOOGLE_VERTEX_AI_MODELO="gemini-2.5-flash-image"
GOOGLE_VERTEX_AI_LOCATION="us-central1"
GOOGLE_VERTEX_AI_PROJECT="generate-image-485916"
GOOGLE_APPLICATION_CREDENTIALS="config/generate-image-485916-b3f3e4a7e693.json"

[AWS]
AWS_BEDROCK_AI_MODELO="anthropic.claude-3-haiku-20240307-v1:0"
AWS_BEDROCK_REGION="us-east-1"
AWS_DYNAMODB_REGION="us-east-1"

[FEATURES]
MAX_IMAGENES_PER_DAY=15