OPENAI_API_KEY="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"
GOOGLE_API_KEY="AIzaSyALyBB7I6_MYnZIpHAVvEB1GMPqAShHEzs"
GEMINI_API_KEY="AIzaSyBLjeqyw4zOcuF4iDMR0E9kHEC7_oK1I68"

[GOOGLE]
GOOGLE_VERTEX_AI_MODELO="gemini-2.5-flash-image"
GOOGLE_VERTEX_AI_LOCATION="us-central1"
GOOGLE_VERTEX_AI_PROJECT="generate-image-485916"
GOOGLE_APPLICATION_CREDENTIALS="config/generate-image-485916-b3f3e4a7e693.json"

[AWS]
AWS_BEDROCK_AI_MODELO="anthropic.claude-3-haiku-20240307-v1:0"
AWS_BEDROCK_REGION="us-east-1"
AWS_DYNAMODB_REGION="us-east-1"

[FEATURES]
MAX_IMAGENES_PER_DAY=15